version: '3.8'

services:
    ### NGINX Server #########################################
    nginx:
        build:
            context: ./docker/nginx
            args:
                - DOCKER_LOCALHOST_SERVERNAME=${DOCKER_LOCALHOST_SERVERNAME}
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-nginx:0.1.0"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - ./docker/nginx/logs/:/var/log/nginx
            #- ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/ssl/:/etc/nginx/ssl
            - .:/var/www/html
        ports:
            - "${DOCKER_NGINX_HOST_HTTP_PORT}:80"
            - "${DOCKER_NGINX_HOST_HTTPS_PORT}:443"
        networks:
            - "${DOCKER_NETWORK}"

    ### APP (php-fpm) ##############################################
    app:
        build:
            context: ./docker/app
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-app:0.1.0"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
            - ./docker/app/supervisor-logs:/var/log
            - .:/var/www/html:delegated
        expose:
            - "9000"
        networks:
            - "${DOCKER_NETWORK}"

    ### DB (MariaDB) ##############################################
    db:
        build:
            context: ./docker/mariadb
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-db:0.1.0"
        restart: always
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.role == manager"
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_USER=${DOCKER_MARIADB_USER}
            - MYSQL_PASSWORD=${DOCKER_MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=root
            - TZ=UTC
        expose:
            - "3306"
#        ports:
#            - "${DOCKER_MARIADB_PORT}:3306"
        networks:
            - "${DOCKER_NETWORK}"

    ### Redis ################################################
    redis:
        build: ./docker/redis
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-redis:0.1.0"
        deploy:
            replicas: 1
        volumes:
            - ./docker/redis/data/:/data
        expose:
            - "6379"
        networks:
            - "${DOCKER_NETWORK}"

    ### Adminer ###########################################
    adminer:
        build:
            context: ./docker/adminer
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-adminer:0.1.0"
        deploy:
            replicas: 1
        environment:
            - ADMINER_DESIGN=flat
            - ADM_DEFAULT_SERVER=db
            - ADMINER_PLUGINS=
        ports:
            - "${DOCKER_ADM_PORT}:8080"
        networks:
            - "${DOCKER_NETWORK}"

    ### Mailhog ################################################
    mailhog:
        build: ./docker/mailhog
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-mailhog:0.1.0"
        deploy:
            replicas: 1
        volumes:
            - ./docker/mailhog/maildir:/home/mailhog/maildir
#        environment:
#            - MH_STORAGE=maildir
#            - MH_MAILDIR_PATH=/home/mailhog/maildir/mails
             ## authentication: mpl:qwe123
#            - MH_AUTH_FILE=/home/mailhog/maildir/auth.txt
        # About command @see https://github.com/mailhog/MailHog/issues/187#issuecomment-733009406
        command: -invite-jim=1
        ports:
            - "${DOCKER_MAILHOG_PORT1}:1025"
            - "${DOCKER_MAILHOG_PORT2}:8025"
        networks:
            - "${DOCKER_NETWORK}"

    ### REDISWEBUI ################################################
    redis-webui:
        build:
            context: ./docker/redis-webui
        image: "${DOCKERHUB_ID}/${DOCKERHUB_PROJECT_REPO_PREFIX}-redis-webui:0.1.0"
        deploy:
            replicas: 1
        environment:
            - ADMIN_USER=${DOCKER_REDIS_WEBUI_USERNAME}
            - ADMIN_PASS=${DOCKER_REDIS_WEBUI_PASSWORD}
            - REDIS_1_HOST=redis
            - REDIS_1_PORT=6379
        networks:
            - "${DOCKER_NETWORK}"
        ports:
            - "${DOCKER_REDIS_WEBUI_PORT}:80"

networks:
    mynetwork: ## !!!the name of network should be the same as ${DOCKER_NETWORK} !!!
        driver: "${DOCKER_NETWORK_DRIVER}"
        ## custom name for network
        ## if omit the name would be something like `mynetwork_mynetwork`
        name: mynetwork

volumes:
    db-data:
        external: true

